# Generated by Django 5.1.5 on 2025-02-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False, verbose_name='UUID')),
                ('cpu', models.IntegerField(verbose_name='Количество процессорных ядер')),
                ('ram', models.IntegerField(verbose_name='Объем оперативной памяти')),
                ('hdd', models.IntegerField(verbose_name='Объем дискового пространства')),
                ('status', models.CharField(choices=[('started', 'запущен'), ('blocked', 'заблокирован'), ('stopped', 'остановлен')], max_length=32, verbose_name='Статус')),
            ],
        ),
    ]
